### ISSUE TITLE
HTTP headers required for reverse-proxy configurations

### ISSUE THREAD

**Issue by dviry** [tpeczek/Lib.AspNetCore.ServerSentEvents#19]
Running my ASP.NET Core app with SSE behind nginx configured as a reverse-proxy, and the sse connection throws many "net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)" errors.

According to [this answer](https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate) it would be enough to appropriately set some headers on response; yet I found no way for me to customize those (except adding an additional middleware before it to set those headers). Would you consider setting those HTTP headers always, or at least provide an extension point (in the ServerSentEventsServiceOptions.cs) to allow configuring those?

Thanks in advance

**Comment by tpeczek** [comment]
I would prefer to add an extension point, my intial thought goes in direction of something similar to what [static files middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2#set-http-response-headers) provides:

```cs
public class Startup
{
    ...

    public void Configure(IApplicationBuilder app)
    {
        ...

        app.MapServerSentEvents("/default-sse-endpoint", new ServerSentEventsOptions
        {
            OnPrepareAccept = response =>
            {
                response.Headers.Append("Cache-Control", "no-cache");
                response.Headers.Append("X-Accel-Buffering", "no");
            }
        });

        ...
    }
}
```

I'm assuming this would solve your case?

**Comment by dviry** [comment]
Hi Tomasz,

I think an extension point would make it bullet proof for future
requirements, so I agree!

Cheers
