### ISSUE TITLE
OnClientConnected and OnClientDisconnected not fired

### ISSUE THREAD

**Issue by draudrau** [tpeczek/Lib.AspNetCore.ServerSentEvents#33]
Hi,

I use your library in the following context :
- Windows authentication
- Cors policy

The library is used in a Web API and events are consumed by two MVC applications.
All with ASP.NET Core 3.1

How I configure the middleware :
```csharp
endpoints.MapServerSentEvents<JobExecutionEventsService>("/sse-notifications", new ServerSentEventsOptions
{
	OnPrepareAccept = (response) =>
	{
		var domainResources = Configuration.GetSection("DomainResources").Get<DomainResourcesOptions>();

		response.Headers.Add("Access-Control-Allow-Origin", domainResources.JobExecBaseUrl);
		response.Headers.Add("Access-Control-Allow-Credentials", "true");
	},
	Authorization = new ServerSentEventsAuthorization
	{
		AuthenticationSchemes = IISDefaults.AuthenticationScheme,
	}
});
```

All is working fine, I can send event to specific user but the events OnClientConnected and OnClientDisconnected are never fired.

I've looked a bit at your code, but I don't understand why it doesn't work.

Thanks for your library wich is realy nice.
Olivier.

**Comment by tpeczek** [comment]
Hi,

I've done some testing today and I wasn't able to reproduce the issue. Can you share the part where you are providing actions for `OnClientConnected` and `OnClientDisconnected`?

**Comment by draudrau** [comment]
For now it's pretty simple :
```csharp
services.AddServerSentEvents<INotificationsServerSentEventsService, JobExecutionEventsService>(config =>
{
    config.OnClientConnected = (service, arg) =>
    {
        Log.Information("SSE connection of user {identityName)", arg.Client.User.Identity.Name);
    };

    config.OnClientDisconnected = (service, arg) =>
    {
        Log.Information("SSE disconnection of user {identityName)", arg.Client.User.Identity.Name);
    }
});
```
When it will work, i'll add some other actions.
Can you send me your Startup.cs file ?

Below my `JobExecutionEventsService` class :
```csharp
public class JobExecutionEventsService : ServerSentEventsService, INotificationsServerSentEventsService
{

    public async Task SendRunStatusAsync(string uid, NotificationLevel level, RunStatus status)
    {
        await base.SendEventAsync(new ServerSentEvent
        {
            Id = uid,
            Type = "RunStatus",
            Data = new List<string> { $"level:{level}", $"status:{status}" }
        });
    }
}
```

**Comment by draudrau** [comment]
If it can help, content of the request when connecting to the SSE endpoint :
```
General:
    Request URL: http://localhost:55009/sse-notifications
    Request Method: GET
    Status Code: 200 OK
    Remote Address: [::1]:55009
    Referrer Policy: no-referrer-when-downgrade

Response Headers:
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: http://localhost:61047
    Content-Encoding: identity
    Content-Type: text/event-stream
    Date: Thu, 16 Apr 2020 16:03:56 GMT
    Persistent-Auth: true
    Server: Microsoft-IIS/10.0
    Transfer-Encoding: chunked
    Vary: Origin
    WWW-Authenticate: Negotiate oRswGaADCgEAoxIEEAEAAAAmg2E4cbBluQAAAAA=
    X-Powered-By: ASP.NET

Request Headers:
    Accept: text/event-stream
    Accept-Encoding: gzip, deflate, br
    Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
    Cache-Control: no-cache
    Connection: keep-alive
    Host: localhost:55009
    Origin: http://localhost:61047
    Referer: http://localhost:61047/
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: same-site
    User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
```

**Comment by tpeczek** [comment]
I think I was able to reproduce it. It seems to be a result of using a custom service, options doesn't seem to be read correctly in that case.

I will work on fix, but meantime you should be able to workaround this by subscribing to events directly in service instead of through options.

```cs
public class JobExecutionEventsService : ServerSentEventsService, INotificationsServerSentEventsService
{
    public JobExecutionEventsService()
    {
        ClientConnected += (service, args) => { System.Diagnostics.Debug.WriteLine(nameof(ClientConnected)); };
        ClientDisconnected += (service, args) => { System.Diagnostics.Debug.WriteLine(nameof(ClientDisconnected)); };
    }

    public async Task SendRunStatusAsync(string uid, NotificationLevel level, RunStatus status)
    {
        await base.SendEventAsync(new ServerSentEvent
        {
            Id = uid,
            Type = "RunStatus",
            Data = new List<string> { $"level:{level}", $"status:{status}" }
        });
    }
}
```

**Comment by henry-chris** [comment]
I've been running this library for months in Azure as a Web App (probably almost a year) and just recently this started occurring.  

OnClientConnected Fires every time correctly, but Disconnected events are never triggered.  

What's funny is my Production server still gets events.  But my Dev/QA servers do not.  If I spin it up on Localhost, I get the events.  

It's really strange.

EDIT:  I am using the events inside a service like in your code above.

**Comment by draudrau** [comment]
> I think I was able to reproduce it. It seems to be a result of using a custom service, options doesn't seem to be read correctly in that case.
> 
> I will work on fix, but meantime you should be able to workaround this by subscribing to events directly in service instead of through options.
> ...

Great, thank you, I will do that.
Have a good day !

**Comment by henry-chris** [comment]
@tpeczek I'm not sure if my problem is the same as @draudrau , but basically in the Middleware it runs to `await context.RequestAborted.WaitAsync();`.

It then registers the cancellationToken callback with source, but the callback is never called.

Clients just keep building up and are never removed as they are never cancelled.

Locally everything is fine. Once I deploy to Azure Web App is when it starts failing.  My Production build went out on 3/29, and works fine.

Sometime after that, all builds (including the build which is currently in production) started failing to cancel clients.  So, I'm wondering if Azure changed something that caused this recently or if it's something else.

EDIT:  I will note that I'm running in a Linux Web App.  I've seen posts/questions about RequestAborted not working there. It also apparently didn't work in Kestrel for some time. 

Hrmm.

**Comment by tpeczek** [comment]
@henry-chris It looks like something different. Probably related to one of the things you have mentioned. Can you create a separate issue? I'll try to investigate and see if anything can be done to mitigate whatever is happening.
