### ISSUE TITLE
Add ReconnectInterval option in ServerSentEventsServiceOptions

### ISSUE THREAD

**Issue by Eli-Black-Work** [tpeczek/Lib.AspNetCore.ServerSentEvents#37]
In our project, we want our `ServerSentEventsService` to be started with a different reconnect interval than the default.

Currently, this seems a bit difficult to do, because `ChangeReconnectIntervalAsync()` is async, so it can't be awaited in the `ServerSentEventsService` constructor.

Could you please add a `ReconnectInterval` field to `ServerSentEventsServiceOptions`, so that the reconnect interval could easily be set when configuring the service?

Thanks :)

**Comment by tpeczek** [comment]
This change makes perfect sens and won't be problematic, so I will take care of adding this.

**Comment by Eli-Black-Work** [comment]
Yay! Thank you :)

**Comment by tpeczek** [comment]
You're welcome
