### ISSUE TITLE
User Claims is Always Empty

### ISSUE THREAD

**Issue by Jarbasjuniorbh** [tpeczek/Lib.AspNetCore.ServerSentEvents#40]
Hi, I'm using IServerSentEventsService.GetClients to get specific clients, but the claims is alwas empty;
![image](https://user-images.githubusercontent.com/9727193/113339549-01d63d00-9301-11eb-81d6-838f06767d0e.png)

Now if check the User in my controller it's ok:

![image](https://user-images.githubusercontent.com/9727193/113339604-14e90d00-9301-11eb-8dce-7075ac29cb9b.png)

**Comment by tpeczek** [comment]
Hi @Jarbasjuniorbh,

This is interesting.

The `IServerSentEventsClient.User` is basically a passthrough to `HttpContext.User`. This suggests to me that either the SSE request and controller request are being made with different auth, or the pipeline for both is different.

Of course there can always be a sneaky bug which I'm missing ;).

Can you provide a minimal reproduction? Maybe a modified branch of [demo project](https://github.com/tpeczek/Demo.AspNetCore.ServerSentEvents).

**Comment by Jarbasjuniorbh** [comment]
Hi @tpeczek,

Thank you for your reply.
The problem was because I'm using a bearer token and I had to pass it through the headers using polyfills: (https://github.com/Yaffle/EventSource).
Now it's loading the claims ok.
Thank you!
