### ISSUE TITLE
Single client clarity...

### ISSUE THREAD

**Issue by leijae** [tpeczek/Lib.AspNetCore.ServerSentEvents#41]
After reading the documentation, I see that the User is exposed as well as the SendEventAsync. However, sending to a single client does seem to be a little more problematic for me.

Things I've tried:
1. Getting a single connected client, selecting a client then sending an event:
```
var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
_eventService.GetClient(userId).SendEventAsync("some message");
```

2. Getting a client from a list of connected Clients:
```
var user = User;
_eventService.GetClients().Single(x => x.User == user).SendEventAsync("some message");
```

both of these result, for me, in a null reference error even though my unit tests show that get clients is populated with the existing claimsprincipal that defines User.

As a less secure work-around I'm just doing:
```
            var sse = new ServerSentEvent
            {
                Id = userId.ToString(),
                Type = messageType,
                Data = new List<string>{"some message"}
            };

return _seventService.SendEventAsync(sse); // TO ALL CLIENTS - on the server
```

and on the client,
```
        var source = new EventSource('/message-channel');
        source.onmessage = function(event) {
            console.log(event.data);
        }

        source.addEventListener('messageType', function (event) {
            alert(event.data);
        });
```

What is actually the CORRECT way of doing this?

**Comment by leijae** [comment]
Ok fantastic. Thanks for the clarity. Just wanted to show you what I'm doing here. With your help I did manage to get it working.

I have a bot using the MS Bot Framework, if a user wants to escalate to an agent they send a request goes to an available agent. So, using SSE, an agent can be anywhere in the application and get the request.

MS did a good job with MS Bot Framework, but they made using the bot as proxy concept incredibly difficult in practice...

![image](https://user-images.githubusercontent.com/50371033/124143107-7596fb80-da50-11eb-9784-519c4bf50834.png)

**Comment by tpeczek** [comment]
Happy to hear that you've managed to get it working and even more happy that you are using this library for interesting stuff :+1:.
