### ISSUE TITLE
InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: 'Server-Sent Events'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.

### ISSUE THREAD

**Issue by rogierhofboer** [tpeczek/Lib.AspNetCore.ServerSentEvents#59]
No matter what I try, I get the following exception when going to the stream, this also happens with the demo app.

InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: 'Server-Sent Events'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.

**Comment by tpeczek** [comment]
Hi @rogierhofboer,

The most common cases when I've seen this error is either a request made to the wrong endpoint or a request made to the correct endpoint but the media type doesn't suggest a Server-Sent Events request. Can you share your request sample?

**Comment by rogierhofboer** [comment]
Hi @tpeczek,

Thanks for your prompt response and for creating this library!

I was just browsing to the endpoint.
With an implementation I used years ago in golang, this was possible and the events just showed up in the browser.
So I expected this to work. I am not sure if with the current specifications this would still be possible / allowed. 
It is however quite handy for debugging.

It works when using plain Javascript to connect :) 

Biggest challenge was getting it working through an nginx reverse proxy...
Only adding the headers suggested here https://tpeczek.github.io/Lib.AspNetCore.ServerSentEvents/articles/advanced.html did not work for me.  Adding the following in the nginx for the location did the trick:

```
proxy_http_version 1.1;
proxy_set_header Connection '';
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;
```

I am not sure (yet) what is exactly needed both on nginx and on the .NET WebApi side, maybe it also possible with less extra extra settings.

**Comment by tpeczek** [comment]
In case of most modern browser, just navigating will make a request with a text/plain or text/html as accepted mime types, so SSE endpoint shouldn't respond to that.

When it comes to nginx (or other proxies) things might be complicated and depend on other configuration already in place, the documentation only covers the most typical settings and ensures that .NET layer doesn't buffer.

**Comment by lefi7z** [comment]
Right, the http header should include `accept: text/event-stream`.

I had the same confusion around this and still don't understand why it leads to an outright server-error when the header is wrong!?

I worked around this by defining a simple middleware before `app.UseEndpoints()` that rejects any other accept-header to my specific endpoint with a `406: Not acceptable`, which seems less confusing to me and gives the client a hint at what to do better.

cheers, appreciate your efforts into this nice library!

**Comment by tpeczek** [comment]
> Right, the http header should include `accept: text/event-stream`.
> 
> I had the same confusion around this and still don't understand why it leads to an outright server-error when the header is wrong!?
> 
> I worked around this by defining a simple middleware before `app.UseEndpoints()` that rejects any other accept-header to my specific endpoint with a `406: Not acceptable`, which seems less confusing to me and gives the client a hint at what to do better.
> 
> cheers, appreciate your efforts into this nice library!

And you did the right thing (by adding that middleware) 👍.

This is the exact intended capability, that comes from ASP.NET Core architecture - middlewares can be pass-through to allow things like content negotiation (for example you could chain another middleware on the same endpoint to support WebSockets as alternative or something else) and avoid baking in decisions on what to do with unhandled requests (for example 400 vs 406).

That said, if I get more feedback that there is a need for this middleware to be terminal, I will be open to add such an option ☺️.
