### ISSUE TITLE
AddAuthorizationCore for .NET Core 3+ versions

### ISSUE THREAD

**Issue by kesik87** [tpeczek/Lib.AspNetCore.ServerSentEvents#61]
Hi,

In generic extension method AddServerSentEvents (ServerSentEventsMiddlewareExtensions class, line 76) there is a piece of code that doesn't seem correct for .NET Core 3.0+ versions:
`services.AddAuthorization();`
Should this be a call to "AddAuthorizationCore"?

Reference: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#authorization-addauthorization-overload-moved-to-different-assembly

**Comment by tpeczek** [comment]
Hi @kesik87,

Can you elaborate on what doesn't seem to be correct? The reference you have provided states following:

> Apps using both methods should see no impact

**Comment by kesik87** [comment]
Hi @tpeczek,

Hmm, indeed. It was super quirkiness of the project I'm migrating to .NET 6 that caused runtime exceptions.. Very sorry for hassle!
