### ISSUE TITLE
Unable to configure ServerSentEventsKeepaliveService without exposing (and having to register ServerSentEventsServiceOptions<ServerSentEventsService>) in DI

### ISSUE THREAD

**Issue by RobThree** [tpeczek/Lib.AspNetCore.ServerSentEvents#63]
Today I wasted 4 hours - if not more - debugging an issue that had me stumped. To be clear: I'm **NOT** blaming you; it was just an unfortunate convergence of circumstances.

I'm doing a project where one of the things I need is SSE. I wrote a few 'wrapper' (or 'proxy') classes to hide a lot of complexity so the main project doesn't have to bother with all sorts of implementation details.

One of the things I did was 'simplify' the options (`ServerSentEventsServiceOptions<ServerSentEventsService>`):

```c#
public class MySentEventsService : ServerSentEventsService
{
    public MySentEventsService(IOptions<MySentEventsServiceOptions> options)
        : base(options?.Value?.ToServerSentEventsServiceOptions())
    {
        //...
    }
}

public class MySentEventsServiceOptions
{
    public TimeSpan KeepaliveInterval { get; init; } = TimeSpan.FromSeconds(20);
    public TimeSpan? ReconnectInterval { get; set; } = null;

    internal IOptions<ServerSentEventsServiceOptions<ServerSentEventsService>>? ToServerSentEventsServiceOptions()
        => Options.Create(new ServerSentEventsServiceOptions<ServerSentEventsService>
        {
            KeepaliveKind = ServerSentEventsKeepaliveKind.Event,
            KeepaliveMode = ServerSentEventsKeepaliveMode.Always,
            KeepaliveInterval = (int)KeepaliveInterval.TotalSeconds,
            ReconnectInterval = (uint?)ReconnectInterval?.TotalSeconds,
        });
}
```

As soon as I used my own options, instead of the previously used `ServerSentEventsServiceOptions<ServerSentEventsService>` the keepalive (which *has* to be `Always`) stopped working. Which is weird since the `ToServerSentEventsServiceOptions` created a correct `IOptions<ServerSentEventsServiceOptions<ServerSentEventsService>>` object.

Turns out, the options passed to the `ServerSentEventsService` constructor are only used in part. As it turns out, the `AddServerSentEvents` extension method registers a `ServerSentEventsKeepaliveService` which I wasn't aware of; I was under the impression the `ServerSentEventsService` handled the keepalives. It took a while for me to realise the `ServerSentEventsKeepaliveService` gets its options directly from DI; there's no way for me to pass options to it explicitly.

To be clear: I'm NOT debating the design of using a separate keepalive service. I think that is a good choice. But the `ServerSentEventsKeepaliveService` gets it's options from the DI framework. Which means I have to register (and expose) the `ServerSentEventsServiceOptions<MySentEventsService>` type. I have no other way to get the keepalive options to the `ServerSentEventsService`.

So my first reaction was to not use the `AddServerSentEvents` extension method but implement my own (doing the same things internally). However, the `NewGuidServerSentEventsClientIdProvider`, `NoOpServerSentEventsNoReconnectClientsIdsStore` and `ServerSentEventsKeepaliveService` are `Internal`. So I can't implement my own DI logic, I *HAVE* to use `AddServerSentEvents`... which in turn results in me having to expose the `ServerSentEventsServiceOptions<MySentEventsService>` which is what I was trying to 'hide' in the first place.

I'm not sure what the best solution would be. I came up with 2 ideas:

1. Make the `NewGuidServerSentEventsClientIdProvider`, `NoOpServerSentEventsNoReconnectClientsIdsStore` and `ServerSentEventsKeepaliveService` public. I don't see a problem in that - but maybe there is a good reason they are `internal`.
2. Provide a way to get options to the `ServerSentEventsKeepaliveService`. I think that would mean adding another (optional) argument to the `AddServerSentEvents` extension method. I'm not a big fan of that.

I think the problem stems from the fact that the `ServerSentEventsServiceOptions` are used to configure both the SSE Service *and* KeepaliveService. Maybe the options should be split into 2 options object - but that would still require above option 1 or 2 for me to be able to configure the KeepaliveService without exposing ServerSentEventsServiceOptions.

Oh, I considered option 3:

3. Create classes that implement `IServerSentEventsClientIdProvider`, `IServerSentEventsNoReconnectClientsIdsStore` and `ServerSentEventsKeepaliveService<T>`, but that would mean a lot of 'duplicate code'.

I'm curious to hear your thoughts about this.

**Comment by tpeczek** [comment]
Hi @RobThree,

Thank you for a very detailed description of the challenge you are facing.

To be honest, I don't think I fully understand what you are trying to achieve. Maybe "what" is not the right term (because you have described it in a lot of details), maybe "why" is better. So I would like to take this discussion a step back. Would you be so kind to show me the API you would like to achieve with your wrapper and what it must hide from other parts of your application?

**Comment by RobThree** [comment]
Explained most simply, I guess, is that I want to create a classlibrary that provides SSE functionality (let's call it `MySSE`) which I can then use in my project(s) (let's call it `MyProject`). The `MySSE` library exposes classes that make it very easy (ea**sier** than your library already does!). So - broadly speaking - I would only have to do something like `var sse = new MySSE('/foo/bar', options)`. All other stuff that' required to use SSE with your library will be handled internally in MySSE.

Now, one of the things I absolutely **need** is a heartbeat. So `MySSE` internally uses the [`AddServerSentEvents`](https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/a5d115fa8b69893ccbe425ed075d6e0c479b57aa/Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddlewareExtensions.cs#L62) method to set up all required services with DI. However, the [`ServerSentEventsKeepaliveService``](https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/a5d115fa8b69893ccbe425ed075d6e0c479b57aa/Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddlewareExtensions.cs#L87) gets it's options ([`IOptions<ServerSentEventsServiceOptions<TServerSentEventsService>>`]) from DI. This means I have to expose `ServerSentEventsServiceOptions<>` (and thus the entire Lib.AspNetCore.ServerSentEvents library) to `MyProject`. I have no way to provide options to the `ServerSentEventsKeepaliveService` from `MyProject` without exposing your lib's classes. And I can't "reimplement" `AddServerSentEvents` in `MySSE` since the `NewGuidServerSentEventsClientIdProvider`, `NoOpServerSentEventsNoReconnectClientsIdsStore` and `ServerSentEventsKeepaliveService` that it sets up are internal.

I hope this makes it more clear, but I agree it's a little confusing. If I have time I'll try to make a testproject. Let me see how quickly I can whip something up...

**Comment by tpeczek** [comment]
Yes, that test project would be great.

Right now it's a little bit unclear for me. Because if you really want to expose some single top-level abstraction and don't expose anything from `Lib.AspNetCore.ServerSentEvents` that means you also don't expose you derived `ServerSentEnventsService` (because it would expose  `Lib.AspNetCore.ServerSentEvents`).

``` cs
public class MySentEventsService : ServerSentEventsService
{
    ...
}
```

If you don't have to expose that class, than it is irrelevant what kind of options it requires, as it is all internal. So you can have your own options object and do all the type mappings at your abstraction entry point completely hidden.

On the other hand, if for some reason you are exposing that `ServerSentEnventsService` implementation, than you are already exposing  `Lib.AspNetCore.ServerSentEvents` which means your options can be simplified and also can inherit from `ServerSentEventsServiceOptions<TServerSentEventsService>` which means that there is `AddServerSentEvents<TIServerSentEventsService, TServerSentEventsService>` waiting for you to use internally and you don't need your own DI registration code.

Or it might be a different scenario which I'm not understanding right and I'm making no sense :).

**Comment by RobThree** [comment]
Ok, I've tried to make a 'minimal' example; unfortunately to stay **somewhat** close to my actual implementation it consists of about a dozen or so files.

[Demo.zip](https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/files/11566657/Demo.zip)

The `program.cs` in the `MyProject` contains some comments to explain how to use the demo.

Assume the `MySSE` is - ultimately - to become a (non public) library for use in some of our projects where I want to hide most of the 'complexity' of Lib.AspNetCore.ServerSentEvents in our 'wrapper classes'.


> On the other hand [...] which means that there is `AddServerSentEvents<TIServerSentEventsService, TServerSentEventsService>` waiting for you to use internally

Yes, but then there will be no `ServerSentEventsKeepaliveService` registered and since it's internal, I can't register manually it either.

Anyway, I hope my example project demonstrates my problem.

**Comment by tpeczek** [comment]
Thanks, I'll try to look at this early next week and see if I can figure out what you desire to achieve and what is the best course of action.

> Yes, but then there will be no `ServerSentEventsKeepaliveService` registered and since it's internal, I can't register manually it either.

I'm not sure what do you mean here. All the overloads of `AddServerSentEvents` are leading to this single implementation which registers everything: https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/a5d115fa8b69893ccbe425ed075d6e0c479b57aa/Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddlewareExtensions.cs#LL62C9-L90C10

So if you have a derived service type, you can always have a derived options type and everything should be registerable without issues.

**Comment by RobThree** [comment]
> Thanks, I'll try to look at this early next week and see if I can figure out what you desire to achieve and what is the best course of action.

Thanks! Much appreciated!

> I'm not sure what do you mean here. All the overloads of `AddServerSentEvents` are leading to this single implementation which registers everything: https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/a5d115fa8b69893ccbe425ed075d6e0c479b57aa/Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddlewareExtensions.cs#LL62C9-L90C10

Yes, correct. However, there's no way for me to pass any options to the ServerSentEvents**KeepaliveService** (without exposing  Lib.AspNetCore.ServerSentEvents).

> So if you have a derived service type, you can always have a derived options type and everything should be registerable without issues.

Even if I had wanted to derive from ServerSentEvents**KeepaliveService**, I can't since it's internal.

Maybe I'm missing something - that's ENTIRELY possible(!). If that's the case then please point me in the right direction.

So, summarizing: What I want to do is:

1. hide Lib.AspNetCore.ServerSentEvents
2. have a way to set the keepalive to anything other than default

If there's a way to do that, I'd love to hear / see how.

**Comment by tpeczek** [comment]
The ServerSentEventsKeepAliveService will pick up the properly registered options for related ServerSentEventsService.

I guess the key part I don't understand here, is why you want to do your own DI registration instead of using the existing one. My simplified way of thinking is:
- If you are exposing a delivered ServerSentEventsService, there should be no issue to have an options class which is also delivered (because you are in fact already exposing the type).
- If you are not exposing any delivered types, then the types you are exposing don't have to be the same types you are using for DI registration. The conversion you are attempting to do in that constructor can be done prior registration and standard registration path can be used.

All of the above is just guessing based on my limited understanding, hopefully the demo project will clear it out for me 🙂.

**Comment by RobThree** [comment]
> The ServerSentEventsKeepAliveService will pick up the properly registered options for related ServerSentEventsService.

Yes, but then I have to register a `ServerSentEventsServiceOptions<MySseService>` and thus expose Lib.AspNetCore.ServerSentEvents, I *could* register the `ServerSentEventsServiceOptions<MySseService>` in my own `AddMySse` extension method, but then we're still registering so I can't get to MY options to get the values from.

> If you are exposing a delivered ServerSentEventsService, there should be no issue to have an options class which is also delivered (because you are in fact already exposing the type).

I'm not exposing Lib.AspNetCore.ServerSentEvents, that's the whole point 😉 

> If you are not exposing any delivered types, then the types you are exposing don't have to be the same types you are using for DI registration. The conversion you are attempting to do in that constructor can be done prior registration and standard registration path can be used.

Yes, but then MY types will be registered in the DI container, which means the KeepAliveService won't find any options (and thus use defaults).

> hopefully the demo project will clear it out for me

I really hope it does 😬  It's hard to explain for me, but I understand it's hard to grasp for you as well.

**Comment by RobThree** [comment]
Oh.

🤦‍♂️ 

Wait.

I'm an idiot.

Hang on.

Edit: Still working on it, but I think I've seen the light 🤣  

Edit 2: Yup. I'm a major idiot 🤦‍♂️ 🙈 

All I needed to do to get the demo fixed was in the `AddMySse` extension method add the following:
```c#
services.AddSingleton(c =>
    {
        var myoptions = c.GetRequiredService<IOptions<MySseOptions>>().Value;
        return Options.Create(new ServerSentEventsServiceOptions<MySseService>()
        {
            KeepaliveInterval = (int)myoptions.KeepaliveInterval.TotalSeconds,
            KeepaliveKind = ServerSentEventsKeepaliveKind.Event,
            KeepaliveMode = ServerSentEventsKeepaliveMode.Always
        });
    }
);
```

....and that can even be simplified / cleaned up more. But this is the gist of it.

I'm an idiot. I'll go sit in the corner with a donkey hat on. I'm sorry to have bothered you. I'll close the issue.

**Comment by RobThree** [comment]
Which, by the way, still leaves the **small** issue that I don't think the keepalive options (`KeepaliveInterval`, `KeepaliveMode`, `KeepaliveKind`, `KeepaliveContent`) should be part of `ServerSentEventsServiceOptions` but belong in a separate class (like `ServerSentEventsKeepaliveOptions` or something). But that will come with it's own challenges too.

Anyway, that's another story and not a real issue to me. I'll get back to my idiot-corner and stay quiet for a while while I sit in shame.

**Comment by tpeczek** [comment]
> Which, by the way, still leaves the **small** issue that I don't think the keepalive options (`KeepaliveInterval`, `KeepaliveMode`, `KeepaliveKind`, `KeepaliveContent`) should be part of `ServerSentEventsServiceOptions` but belong in a separate class (like `ServerSentEventsKeepaliveOptions` or something). But that will come with it's own challenges too.
> 
> Anyway, that's another story and not a real issue to me. I'll get back to my idiot-corner and stay quiet for a while while I sit in shame.

Happy to hear that our conversation has helped you to get what you want, sometimes all we need is a rubber duck 🙂.

When it comes to aspect of separating the options - yes that is something to think of. It would be a breaking a significant change, I guess this will have to cook for a while.

**Comment by RobThree** [comment]
> sometimes all we need is a rubber duck

That's the worst part, I have an actual rubber duck 🤣 But thanks for sticking with me!

> When it comes to aspect of separating the options - yes that is something to think of. It would be a breaking a significant change, I guess this will have to cook for a while.

No hurry, it's just something to consider indeed. Again, thanks!
