### ISSUE TITLE
Supplying multiple Accept headers does not work.

### ISSUE THREAD

**Issue by krebil** [tpeczek/Lib.AspNetCore.ServerSentEvents#64]
The issue is roughly the same as: https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/970

In this method: https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/a5d115fa8b69893ccbe425ed075d6e0c479b57aa/Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs#L117C2-L135C10

```
private bool CheckAcceptHeader(IHeaderDictionary requestHeaders)
{
            if (!requestHeaders.ContainsKey(Constants.ACCEPT_HTTP_HEADER))
            {
                return !_serverSentEventsOptions.RequireAcceptHeader;
            }


            if (requestHeaders[Constants.ACCEPT_HTTP_HEADER].Count == 0)
            {
                return !_serverSentEventsOptions.RequireAcceptHeader;
            }


            if (requestHeaders[Constants.ACCEPT_HTTP_HEADER].Any(acceptHeaderValue => acceptHeaderValue == Constants.SSE_CONTENT_TYPE))
            {
                return true;
            }


            return false;
}
```

`requestHeaders[Constants.ACCEPT_HTTP_HEADER]` returns a single string. So if my accept header would include both **text/event-stream** and **text/html**. Then the string would look like "text/event-stream, text/html" which would never match the SSE_CONTENT_TYPE.

If we update the above line with [GetCommaSeparatedValues](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.headerdictionaryextensions.getcommaseparatedvalues?view=aspnetcore-7.0) Then the snippet should work.

Eg.  
`if (requestHeaders.GetCommaSeparatedValues(Constants.ACCEPT_HTTP_HEADER).Any(acceptHeaderValue => acceptHeaderValue == Constants.SSE_CONTENT_TYPE))`

**Comment by krebil** [comment]
I would be happy to supply a pull request :)

**Comment by tpeczek** [comment]
> I would be happy to supply a pull request :)

I would be happy to accept it. Would you be so kind to add an appropriate test case to [handshake tests](https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/blob/main/Test.AspNetCore.ServerSentEvents/Unit/Middleware/HandshakeTests.cs)?

**Comment by krebil** [comment]
Yes that's no problem.
