### ISSUE TITLE
Some accept headers have unexpected behavior 

### ISSUE THREAD

**Issue by krebil** [tpeczek/Lib.AspNetCore.ServerSentEvents#66]
Some accept headers behave unexpectedly. 
For example the **\*/\*** media type does not allow the ServerSentEventMiddleware to trigger. 

If the accept header text/event-stream is configured as **not** required then sending any accept header except text/event-stream will cause ServerSentEventMiddleware to not trigger properly. Which indirectly makes omitting accept headers required (unless the acceot header includes **text/event-stream**).

I propose two changes:

1. allow **\*/\*** to pass the accept headers check regardless of configuration. (This is also the standard accept header in postman so it might make barrier of entry lower)
2. make the check for accept headers exit early if the environment is configured to not require **text/event-stream** present in the accept headers. Skipping all other checks and returning true.

**Comment by tpeczek** [comment]
> I propose two changes:
> 
> 1. allow ***/*** to pass the accept headers check regardless of configuration. (This is also the standard accept header in postman so it might make barrier of entry lower)
> 2. make the check for accept headers exit early if the environment is configured to not require **text/event-stream** present in the accept headers. Skipping all other checks and returning true.

This is a little bit more tricky and I only partially agree at this point (although I'm always open for discussion).

Ad 1. Yes, I agree that `*/*` should be supported (and `text/*` probably as well as we are at it).

Ad 2. The behaviour you described for `RequireAcceptHeader` is as designed. It is supposed to allow making a request without an `Accept` header, as spec for Server-Sent Events does allow that. Originally the behaviour was the default, but it has proven to be to aggressive (#52) so it has been parameterised. My opinion at this point is that this behaviour shouldn't be extended to handle request which have `Accept` header which doesn't indicate Server-Sent Events as understandable response content.

**Comment by krebil** [comment]
@tpeczek 
Let's leave the discussion of the second point for a different time then.

Would you be open to a PR for the first point?

**Comment by tpeczek** [comment]
> Would you be open to a PR for the first point?

Yes, of course 😊
