### ISSUE TITLE
builder.Services.AddServerSentEventsClientIdProvider<CookieBasedServerSentEventsClientIdProvider>(); throws errors

### ISSUE THREAD

**Issue by sudipbhujel** [tpeczek/Lib.AspNetCore.ServerSentEvents#72]
I am getting problems while adding cookie based server sent events clientid provider.
```
System.InvalidOperationException: Headers are read-only, response has already started.
```
<img width="1128" alt="Screenshot 2023-12-19 at 12 54 32 PM" src="https://github.com/tpeczek/Lib.AspNetCore.ServerSentEvents/assets/40120812/7a69971a-0aae-4c80-8311-f58667777bd8">

**Comment by tpeczek** [comment]
Hi @sudipbhujel,

As this library doesn't provide the `CookieBasedServerSentEventsClientIdProvider`, I'm assuming that you are rolling your own implementation based on the simplistic implementation mentioned in the documentation. The implementation from the documentation is there only as food for thought and is very naive (the documentation is clear that it is not suitable for production). It basically handles only one-time connections and reconnect prevention in simple cases, but it doesn't even handle disconnect properly as `ReleaseClientId` attempts to blindy delete a cookie which is not valid for clean reconnect (this is most likely what you are hitting if you attempted to use the sample as-it-is).

**Comment by sudipbhujel** [comment]
Thank you @tpeczek. I got you.
