### ISSUE TITLE
How to handle SSE responses independently for each HTTP request like ChatGPT?

### ISSUE THREAD

**Issue by STARKXu** [tpeczek/Lib.AspNetCore.ServerSentEvents#76]
The documentation seems to lean towards Redis' publish/subscribe functionality, but I don't understand how to return data independently for each HTTP request, similar to how ChatGPT responds.

**Comment by tpeczek** [comment]
Every "request" is represented as a client ('[IServerSentEventsClient](https://tpeczek.github.io/Lib.AspNetCore.ServerSentEvents/api/Lib.AspNetCore.ServerSentEvents.IServerSentEventsClient.html)') to which you can send events [directly](https://tpeczek.github.io/Lib.AspNetCore.ServerSentEvents/articles/getting-started.html#sending-to-specific-client).

You can also utilize the '[ClientConnected](https://tpeczek.github.io/Lib.AspNetCore.ServerSentEvents/api/Lib.AspNetCore.ServerSentEvents.IServerSentEventsService.html#Lib_AspNetCore_ServerSentEvents_IServerSentEventsService_ClientConnected)' event to kick-off a client-specific background processing which will later send events to this client (you can transfer there reference to the client object or just the client identifier based on which you can retrieve client object later).
